### ISSUE TITLE
Generator turns integer and enum option values into strings 

### ISSUE THREAD

**Issue by johan-groenenboom** [criccomini/proto-schema-parser#33]
When parsing:  
```
syntax = "proto3";
package test.v1.proto_1;
import "test/options/v1/option_extensions.proto";
service TestService {
  option (test.options.v1.service_lifecycle) = SERVICE_LIFECYCLE_UNPUBLISHED;
  option (test.options.v1.major_version) = 1;
  option (test.options.v1.minor_version) = 2;
  option (test.options.v1.patch_version) = 3;
  rpc TestMethod (TestRequest) returns (TestResponse);
}
message TestRequest {}   
message TestResponse {}
```

And putting the output of Parser().parse back into Generator().generate(), the result is as shown below, with all the option values turned into strings:    

```
syntax = "proto3";
package test.v1.proto_1;
import "test/options/v1/option_extensions.proto";
service TestService {
  option (test.options.v1.service_lifecycle) = "SERVICE_LIFECYCLE_UNPUBLISHED";
  option (test.options.v1.major_version) = "1";
  option (test.options.v1.minor_version) = "2";
  option (test.options.v1.patch_version) = "3";
  rpc TestMethod (TestRequest) returns (TestResponse);
}
message TestRequest {
}
message TestResponse {
}
```

**Comment by criccomini** [comment]
Yes, the parser doesn't know what the data types are for options, so it treats everything as a string:

```python
    def visitOptionDecl(self, ctx: ProtobufParser.OptionDeclContext):
        name = self._getText(ctx.optionName())
        value = self._getText(ctx.optionValue())
        return ast.Option(name=name, value=value)
```

**Comment by criccomini** [comment]
Fixed and released in 1.3.8:

https://pypi.org/project/proto-schema-parser/1.3.8/

**Comment by johan-groenenboom** [comment]
Hi Chris, thanks for the fast response. Awesome! - Johan

**Comment by johan-groenenboom** [comment]
I did some testing on the new version, I still got the same result:
```
PROTO_TEXT = '''
syntax = "proto3";
package test.v1.proto_1;
service TestService {
    option (test.options.v1.lifecycle) = DEPRECATED;
    option (test.options.v1.major_version) = 1;
}
'''
ast = Parser().parse(PROTO_TEXT)
gen = Generator().generate(ast)
print(gen)
```
Gives this output:

```
syntax = "proto3";
package test.v1.proto_1;
service TestService {
  option (test.options.v1.lifecycle) = "DEPRECATED";
  option (test.options.v1.major_version) = "1";
}
```

So the option values are still output as strings. I guess the criteria (for the parser) for a value being a string is simply that it has quotes, otherwise it's something else.

**Comment by criccomini** [comment]
Ah! I think I might be defaulting all options to string on output. Lemme check

**Comment by criccomini** [comment]
Fixing here: https://github.com/criccomini/proto-schema-parser/pull/36

**Comment by johan-groenenboom** [comment]
I left some comments

**Comment by criccomini** [comment]
K, I think it should work now. Lemme publish a release.

**Comment by johan-groenenboom** [comment]
The new 1.3.9 release doesn't load in my Python 3.8.1 environment - I get a TypeError:
File "C:\Python38\lib\site-packages\proto_schema_parser\parser.py", line 41, in ASTConstructor
    def visitOptionValue(self, ctx: ProtobufParser.OptionValueContext | Any):
TypeError: unsupported operand type(s) for |: 'type' and '_SpecialForm'

If I remove the Any, similar errors pop up in several other places, such as generator.py line 206 and parser.py line 267

**Comment by criccomini** [comment]
Gah, my bad. I did Python 3.10 syntax. Fixing.

**Comment by criccomini** [comment]
Just published 3.10 @johan-groenenboom.

https://pypi.org/project/proto-schema-parser/1.3.10/

LMK how it goes!

**Comment by johan-groenenboom** [comment]
Hi Chris, thanks! The use cases I submitted for this issue are now handled transparently by a parser->generator cycle. All good there.
I do have another use case that still fails, but I will open a separate issue for that.
